In [2]:
# TENSORFLOW 

import tensorflow as tf 
print('Tensorflow version: {}'.format(tf.__version__))

Tensorflow version: 2.8.0


In [6]:
# Loading a dataset 
mnist = tf.keras.datasets.mnist 

(x_train, y_train), (x_test, y_test) = mnist.load_data() 


In [7]:
x_train, x_test = x_train / 255.0, x_test / 255.0 
# pixel images range from 0 to 255
# scale by to range 0 to 1 by dividing by 255 

In [8]:
# Build machine learning model 
# Sequential is useful for stacking layers where each layer 
# has one input tensor and one output tensor 
# Layers are functions with know math structure that can be reused and have trainable variables 
# Most tensor models are composed of layers ie Flatten, Dense, Dropout etc 
# Flatten ?? # Dense ?? # Dropout ??
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)), 
    tf.keras.layers.Dense(128, activation='relu'), 
    tf.keras.layers.Dropout(0.2), 
    tf.keras.layers.Dense(10)
])

In [9]:
predictions = model(x_train[:1]).numpy()
predictions 

array([[-0.23390253, -0.02438065,  0.23565167, -0.32434618,  0.100757  ,
         0.6025284 , -0.23720473, -0.29238352, -0.22445783, -0.5639548 ]],
      dtype=float32)

In [10]:
# softmax function converts these logits to probabilities 
# what are logits ?? 
tf.nn.softmax(predictions).numpy()

array([[0.08250996, 0.10174208, 0.13195662, 0.07537498, 0.11530474,
        0.19044243, 0.08223794, 0.07782308, 0.08329294, 0.05931527]],
      dtype=float32)

In [11]:
# Loss functions => takes a vector of ground truth values and vector of logits and 
# returns a scalar loss for each example. 
# The loss is equal to the negative log probability of the true class: 
# The loss is zero if the model is sure of the correct class 

In [13]:
# The untrained model gives probabilities close to random (1/10 for each class),
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [14]:
loss_fn(y_train[:1], predictions).numpy()

1.6584053

In [15]:
# Before training, configure and compile the model using Model.compile
# set optimiser class to adam
# what is adam ?? 
# set the loss function to loss_fn 
# specify metric to be evaluated for the model setting metrics parameter to accuracy 
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

In [16]:
# Train and evaluate the model 
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
   1/1875 [..............................] - ETA: 4:10 - loss: 2.3910 - accuracy: 0.0312

2023-02-06 21:20:06.639554: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


1875/1875 [==============================] - 2s 779us/step - loss: 0.2917 - accuracy: 0.9147
Epoch 2/5
1875/1875 [==============================] - 1s 706us/step - loss: 0.1421 - accuracy: 0.9576
Epoch 3/5
1875/1875 [==============================] - 1s 776us/step - loss: 0.1053 - accuracy: 0.9679
Epoch 4/5
1875/1875 [==============================] - 1s 698us/step - loss: 0.0866 - accuracy: 0.9737
Epoch 5/5
1875/1875 [==============================] - 1s 700us/step - loss: 0.0755 - accuracy: 0.9767


In [17]:
# Evaluate the model 
# model.evaluate method checks the models performance 
# on a validation or test set 
model.evaluate(x_test, y_test, verbose=2) 

313/313 - 0s - loss: 0.0729 - accuracy: 0.9787 - 168ms/epoch - 537us/step


[0.07286735624074936, 0.9786999821662903]

In [18]:
# model returning a probability 
# wrap the model and attach a softmax to it 
probability_model = tf.keras.Sequential([
    model, 
    tf.keras.layers.Softmax() 
])

In [19]:
probability_model(x_test[:5]) 

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.08611204e-07, 7.48802886e-09, 5.10687471e-07, 1.02870421e-04,
        2.38524803e-12, 5.80084532e-08, 3.68023068e-15, 9.99893904e-01,
        4.98047825e-09, 2.64570895e-06],
       [4.14421102e-08, 1.88761132e-05, 9.99919653e-01, 6.14003220e-05,
        4.35039854e-16, 8.25296382e-08, 7.74368569e-09, 1.65879720e-13,
        5.71561358e-08, 5.76002868e-14],
       [2.60346246e-06, 9.97812748e-01, 1.94906301e-04, 4.32227826e-05,
        1.44998790e-04, 6.52961126e-06, 2.33972205e-05, 1.24460843e-03,
        5.25229436e-04, 1.76925960e-06],
       [9.99969125e-01, 9.91235094e-10, 1.21533258e-05, 7.06755657e-07,
        8.74994388e-09, 4.01597526e-06, 8.88716295e-06, 1.73568890e-06,
        4.30779323e-08, 3.25575184e-06],
       [7.56267127e-06, 4.28869784e-09, 6.25637040e-05, 2.02885943e-07,
        9.88426745e-01, 2.62497474e-06, 9.19672038e-06, 6.97203795e-04,
        6.50214361e-06, 1.07873715e-02]], dtype=float32)>